# branches to build
branches:
  # whitelist
  only:
    - master

# build version format
version: '{build}'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 14
    - nodejs_version: 16

# Get the stable version of node
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@6
  - node --version
  - npm --version
  - npm install
  - npm install -g grunt-cli

build: off

test_script:
  - cmd: npm test
